spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      routes:
        - id: "product-service"
          uri: "http://localhost:1483"
          predicates:
            - Path=/api/products/**

server:
    port: 8080

